# Distributed revision control system
brew "git"

# Display directories as trees (with optional color/HTML output)
brew "tree"

# Applications and Tools
cask "docker"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "postman"

# QuickLook plugins
cask "qlcolorcode"
cask "qlgradle"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "webpquicklook"
