zmodload zsh/zprof

#------------------------------
# Variables
#------------------------------
ZDOTDIR=${ZDOTDIR:-${HOME}}
ZSHDDIR="${HOME}/.config/zsh.d"
HISTFILE="${ZDOTDIR}/.zsh_history"
HISTSIZE="1000"
SAVEHIST="${HISTSIZE}"
LS_COLORS="rs=0:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:";

export BROWSER="chrome"
export EDITOR=$(which subl)
export LS_COLORS

## -----------------------------------
## zsh options
## -----------------------------------
# Keep history of `cd` as in with `pushd` and make `cd -<TAB>` work. Dirstack
# DIRSTACKFILE="$HOME/.cache/zsh/dirs"
# if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
#   dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
#   [[ -d $dirstack[1] ]] && cd $dirstack[1]
# fi
# chpwd() {
#   print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
# }
DIRSTACKSIZE=16
setopt auto_pushd pushd_silent pushd_to_home

## Remove duplicate entries
setopt pushd_ignore_dups

## This reverts the +/- operators.
setopt pushd_minus

# Ignore lines prefixed with '#'.
setopt interactivecomments

# Ignore duplicate in history.
setopt hist_ignore_dups

# Prevent record in history entry if preceding them with at least one space
setopt hist_ignore_space

# Nobody need flow control anymore. Troublesome feature.
#stty -ixon
setopt noflowcontrol

# Auto cd into directory by name
setopt auto_cd

# Ensure that / is added after tab complation to directories.
# without disabling it, $LBUFFER does not have the slash at the end
# and it's required for _append_path_to_buffer thing..
setopt AUTO_PARAM_SLASH
unsetopt AUTO_REMOVE_SLASH


## -----------------------------------
# Completion
## -----------------------------------
# Load zsh completion
fpath=(/usr/local/share/zsh-completions $fpath)

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Completions
zstyle ':completion:*' menu select=2 select=long-list
zstyle ':completion:*' rehash true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:descriptions' format '%U%F{cyan}%d%f%u'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

#------------------------------
# Window title
#------------------------------
case $TERM in
  termite|*xterm*|rxvt|rxvt-unicode|rxvt-256color|rxvt-unicode-256color|(dt|k|E)term)
    precmd () {
      #vcs_info
      print -Pn "\e]0;[%n@%M][%~]%#\a"
    } 
    preexec () { print -Pn "\e]0;[%n@%M][%~]%# ($1)\a" }
    ;;
  screen|screen-256color)
    precmd () { 
      #vcs_info
      print -Pn "\e]83;title \"$1\"\a" 
      print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~]\a" 
    }
    preexec () { 
      print -Pn "\e]83;title \"$1\"\a" 
      print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~] ($1)\a" 
    }
    ;; 
esac

## -----------------------------------
## File manager key binds
## -----------------------------------
cdUndoKey() {
  popd
  zle       reset-prompt
  echo
  ls
  zle       reset-prompt
}

cdParentKey() {
  pushd ..
  zle       reset-prompt
  echo
  ls
  zle       reset-prompt
}

zle -N                 cdParentKey
zle -N                 cdUndoKey
bindkey '^[[1;3A'      cdParentKey
bindkey '^[[1;3D'      cdUndoKey

## -----------------------------------
## iTerm shell integrations
## -----------------------------------
test -e "${HOME}/.shell_config/iterm2/iterm2_shell_integration.zsh" && source "${HOME}/.shell_config/iterm2/iterm2_shell_integration.zsh"


## -----------------------------------
## Zsh Plugins
## -----------------------------------

# Plugin "k"
test -e "${HOME}/.shell_config/zsh_plugins/k/k.sh" && source "${HOME}/.shell_config/zsh_plugins/k/k.sh"


#------------------------------
# Load Zsh tools for syntax highlighting and autosuggestions
#------------------------------
source "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh"


## -----------------------------------
## Zsh theme
## -----------------------------------
test -e "${HOME}/.shell_config/zsh_theme.sh" && source "${HOME}/.shell_config/zsh_theme.sh"


## -----------------------------------
## Load .profile for common elements
## -----------------------------------
test -e "${HOME}/.profile" && source "${HOME}/.profile"


## -----------------------------------
## Path updates
## -----------------------------------

# eliminates duplicates in *paths
typeset -gU cdpath fpath path

# Zsh search path for executable
path=(
  /usr/local/{bin,sbin}
  $path
)


## -----------------------------------
# Load compinit
## -----------------------------------
zmodload zsh/complist 
autoload -Uz compinit
compinit
zstyle :compinstall filename '${HOME}/.zshrc'
# if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
#   compinit -D
#   zstyle :compinstall filename '${HOME}/.zshrc'
#   {
#     # Compile zcompdump, if modified, to increase startup speed.
#     zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
#     if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
#       zcompile "$zcompdump"
#     fi
#   } &!
# else
#   compinit -C
# fi

# added by travis gem
[ ! -s /Users/arpit/.travis/travis.sh ] || source /Users/arpit/.travis/travis.sh
